name: date_calc
description: Date manipulation library for Dart. It provides a class that inherits from the DateTime class, makes it easy to calculate additions, subtractions and so on.
version: 0.2.0
author: makicamel <unright@gmail.com>
homepage: https://github.com/makicamel/date_calc

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.4.0
  intl: ^0.17.0

dev_dependencies:
  test: ^1.17.9
